"""
    Figures layout

Generation of the layouts and formats of the figures.
"""

# Specify the figure dimensions and style
fig = Figure(; size = (1200, 1200))

# Set thickness and size of axes elements 
border = 2.0
labels = 20
ticks = 22

# μ = -0.3
ax1_top = Axis(fig[1,1], limits = (-1,1,-0.35,0.5), 
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = false,
               ylabelvisible = true,
               xticklabelsvisible = false,
               yticklabelsvisible = true,
               xtickalign = 1,
               ytickalign = 1,
               xticks = [-1,0,1],
               yticks = [-0.35,0,0.5],
               #xticksize = ticks,
               #yticksize = ticks,
               xtickwidth = border,
               ytickwidth = border,
               ylabel = L"\textbf{potential}",
               ylabelsize = labels,
               yticklabelsize = labels,
              )
ax1_mid = Axis(fig[2:3,1], limits = (-1,1,0,Nt*dt),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = false,
               ylabelvisible = true,
               xticklabelsvisible = false,
               yticklabelsvisible = true,
               xtickalign = 1,
               ytickalign = 1,
               yreversed = true,
               xticks = [-1,0,1],
               yticks = [0,Nt*dt],
               xtickwidth = border,
               ytickwidth = border,
               ylabel = L"\textbf{time}",
               ylabelsize = labels,
               yticklabelsize = labels,
              )
ax1_bot = Axis(fig[4,1], limits = (-1,1,0,6.5),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = true,
               ylabelvisible = true,
               xticklabelsvisible = true,
               yticklabelsvisible = true,
               xtickalign = 1,
               ytickalign = 1,
               xticks = [-1,0,1],
               yticks = [0,6.5],
               xtickwidth = border,
               ytickwidth = border,
               xlabel = L"\textbf{state}",
               ylabel = L"\textbf{distribution}",
               xlabelsize = labels,
               ylabelsize = labels,
               xticklabelsize = labels,
               yticklabelsize = labels,
              )

# μ = 0.0 (Maxwell point)
ax2_top = Axis(fig[1,2], limits = (-1,1,-0.35,0.5),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = false,
               ylabelvisible = false,
               xticklabelsvisible = false,
               yticklabelsvisible = false,
               xtickalign = 1,
               ytickalign = 1,
               xticks = [-1,0,1],
               yticks = [-0.35,0,0.5],
               xtickwidth = border,
               ytickwidth = border,
              )
ax2_mid = Axis(fig[2:3,2], limits = (-1,1,0,Nt*dt),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = false,
               ylabelvisible = false,
               xticklabelsvisible = false,
               yticklabelsvisible = false,
               xtickalign = 1,
               ytickalign = 1,
               yreversed = true,
               xticks = [-1,0,1],
               yticks = [0,Nt*dt],
               xtickwidth = border,
               ytickwidth = border,
              )
ax2_bot = Axis(fig[4,2], limits = (-1,1,0,6.5),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = true,
               ylabelvisible = false,
               xticklabelsvisible = true,
               yticklabelsvisible = false,
               xtickalign = 1,
               ytickalign = 1,
               xticks = [-1,0,1],
               yticks = [0,6.5],
               xlabel = L"\textbf{state}",
               xlabelsize = labels,
               xticklabelsize = labels,
               xtickwidth = border,
               ytickwidth = border,
              )

# μ = +0.3
ax3_top = Axis(fig[1,3], limits = (-1,1,-0.35,0.5),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = false,
               ylabelvisible = false,
               xticklabelsvisible = false,
               yticklabelsvisible = false,
               xtickalign = 1,
               ytickalign = 1,
               xticks = [-1,0,1],
               yticks = [-0.35,0,0.5],
               xtickwidth = border,
               ytickwidth = border,
              )
ax3_mid = Axis(fig[2:3,3], limits = (-1,1,0,Nt*dt),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = false,
               ylabelvisible = false,
               xticklabelsvisible = false,
               yticklabelsvisible = false,
               xtickalign = 1,
               ytickalign = 1,
               yreversed = true,
               xticks = [-1,0,1],
               yticks = [0,Nt*dt],
               xtickwidth = border,
               ytickwidth = border,
              )
ax3_bot = Axis(fig[4,3], limits = (-1,1,0,6.5),
               spinewidth = border,
               xgridvisible = false,
               ygridvisible = false,
               xlabelvisible = true,
               ylabelvisible = false,
               xticklabelsvisible = true,
               yticklabelsvisible = false,
               xtickalign = 1,
               ytickalign = 1,
               xticks = [-1,0,1],
               yticks = [0,6.5],
               xlabel = L"\textbf{state}",
               xlabelsize = labels,
               xticklabelsize = labels,
               xtickwidth = border,
               ytickwidth = border,
              )

# Array of axes
axes = [[ax1_top, ax1_mid, ax1_bot], [ax2_top, ax2_mid, ax2_bot], [ax3_top, ax3_mid, ax3_bot]]

# Adjust whitespace between columns and rows
colgap!(fig.layout, 120)
