"""
    Postprocessing script

Collection of quantities and functions used to postprocess and analyse the results of a simulation.
"""

# Parameters of the scalar potential method
Nc = convert(Int64, 3e0)                                                # Solution space dim. of the method 
Na = convert(Int64, 1e4)                                                # Number of attempts per guess 
Nx = 0::Integer                                                         # Number of escapes prior to the end of the simulation
β = 1e-3                                                                # Std of the guess perturbation 

# Scalar potential of the conservative system 
U(x, y, μ) = (x^2 - 1)^2 + y^2 + μ*x            # Ground truth
U0(x, y, μ) = U(a11*x + a12*y, a21*x + a22*y, μ)# Rotated ground truth
V(x, c) = c[1]*x + c[2]*(x^2) + c[3]*(x^3)      # Arbitrary cubic potential
 
# Data structures
solutions = Vector{Vector{Float64}}()           # Solutions of the inference method 
results = Vector{Float64}()                     # Statistical distribution over the ensemble

# Shift the reconstructed potential to match the local minimum of the ground truth
function shift_potential(V::Function, parameter, subspace, c, equilibrium)
        # Compute the stable equilibrium (center of the shift)
        xs = +(1/(3*c[3]))*(sqrt((c[2])^2 - 3*c[1]*c[3]) - c[2])

        # Compute the shifts
        x0 = (equilibrium[1] + subspace*equilibrium[2])/(sqrt(1 + subspace^2))
        δx = x0 - xs 
        δy = V(x0) - (Polynomial([0.0; c]))(xs)

        # Define the shifted potential
        Vs(x) = δy + c[1]*(x - δx) + c[2]*(x - δx)^2 + c[3]*(x - δx)^3

        return xs, Vs
end

# Computes the 1-dimensional subspace associated to the desired observable
function compute_subspace(μ)
        # Define the generating vector field of the original potential
        f1(x, y, p) = -p + 4*x -4*x^3 
        f2(x, y, p) = -2*y 

        # Compute the equilibria of the vector field
        equilibria = get_equilibria(f1, f2, μ)

        # Compute the images of the two co-linear points under A
        x1 = inv(A)*equilibria.stable[1]
        x2 = inv(A)*equilibria.stable[2]

        # Compute the slope of the line connecting the two new points
        m = (x2[2] - x1[2])/(x2[1] - x1[1])
        return m
end

# Computes the optimal subspace associated to the principal component of the data 
function compute_optimal(X)
        # Center the data
        X = X .- mean(X, dims=1)

        # Compute the covariance matrix
        Σ = (transpose(X)*X)/(size(X,1)-1)

        # Perform eigendecomposition
        λ = eigen(Σ, sortby=-).values
        V = eigen(Σ, sortby=-).vectors

        # Take largest eigenvalue (principal component)
        idx = sortperm(λ, rev=true)
        λ = λ[idx]
        V = V[:, idx]
        v = V[:,1]

        # Compute the slope of the line generated by the principal component
        m = v[2]/v[1]

        return m 
end

# Compute observables associated to the 3 subspaces (optimal, perturbed, suboptimal)
function compute_observables(data, μ)
        # Compute the optimal subspace and its basis 
        α = compute_optimal(data)
        u = [1, α]
        # Compute the observable by projection onto the subspace
        ψ = [dot([data[n,1], data[n,2]], u) for n in 1:size(data, 1)]./norm(u, 2)

        # Compute the perturbed subspace and its basis vector 
        β = compute_subspace(μ)
        v = [1, β]
        # Compute the observable by projection onto the subspace
        φ = [dot([data[n,1], data[n,2]], v) for n in 1:size(data, 1)]./norm(v, 2)

        # Compute the suboptimal subspace and its basis vector
        γ = -8.0
        w = [1, γ]
        # Compute the observable by projection onto the subspace
        ω = [dot([data[n,1], data[n,2]], w) for n in 1:size(data, 1)]./norm(w, 2)

        return (
                optimal = ψ,
                perturbed = φ,
                suboptimal = ω,
                subspaces = [α, β, γ]
               )
end

function analyse(solutions, parameter)
        # Compute estimated stable and unstable equilibria of the cubic
        xs = +(1/(3*solutions[3]))*(sqrt((solutions[2])^2 - 3*solutions[1]*solutions[3]) - solutions[2])
        xu = -(1/(3*solutions[3]))*(sqrt((solutions[2])^2 - 3*solutions[1]*solutions[3]) + solutions[2])

        # Compute the escape rate's components
        ΔV = abs(V(xu, solutions) - V(xs, solutions))
        ews = exp(-ΔV)

        return ews
end
