"""
    Figures layout

Generation of the layouts and formats of the figures.
"""

# Specify the figure dimensions and style
fig = Figure(; size = (1300, 650), figure_padding = (30,30,30,30))

# Set thickness and size of axes elements 
border = 2.0
labels = 20
ticks = 22

# Variance EWS
ax1L = Axis(fig[1,1],
            limits = (-0.9, 0.0, 0.0, 0.1),
            spinewidth = border,
            title = L"\text{SN}",
            titlesize = labels,
            xgridvisible = false,
            ygridvisible = false,
            xlabelvisible = false,
            ylabelvisible = true,
            xticklabelsvisible = false,
            yticklabelsvisible = true,
            xtickalign = 1,
            ytickalign = 1,
            xtickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            ytickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            xtickwidth = border,
            ytickwidth = border,
            xlabel = L"\mu",
            ylabel = L"\text{Var}(x)",
            xlabelsize = labels,
            ylabelsize = labels,
            xticklabelsize = labels,
            yticklabelsize = labels,
           )

ax1M = Axis(fig[1,2],
            limits = (1.8, 2.6, 0.0, 0.1),
            spinewidth = border,
            title = L"\text{May}",
            titlesize = labels,
            xgridvisible = false,
            ygridvisible = false,
            xlabelvisible = false,
            ylabelvisible = false,
            xticklabelsvisible = false,
            yticklabelsvisible = false,
            xtickalign = 1,
            ytickalign = 1,
            xtickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            ytickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            xtickwidth = border,
            ytickwidth = border,
            xlabel = L"\mu",
            ylabel = L"\text{Var}(x)",
            xlabelsize = labels,
            ylabelsize = labels,
            xticklabelsize = labels,
            yticklabelsize = labels,
           )

ax1R = Axis(fig[1,3],
            limits = (0.1, 1.2, 0.0, 0.1),
            spinewidth = border,
            title = L"\text{Stommel}",
            titlesize = labels,
            xgridvisible = false,
            ygridvisible = false,
            xlabelvisible = false,
            ylabelvisible = false,
            xticklabelsvisible = false,
            yticklabelsvisible = false,
            xtickalign = 1,
            ytickalign = 1,
            xtickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            ytickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            xtickwidth = border,
            ytickwidth = border,
            xlabel = L"\mu",
            ylabel = L"\text{Var}(x)",
            xlabelsize = labels,
            ylabelsize = labels,
            xticklabelsize = labels,
            yticklabelsize = labels,
           )

# Modified escape EWS
ax2L = Axis(fig[2,1],
            limits = (-0.9, 0.0, 0.0, 1.0),
            spinewidth = border,
            xgridvisible = false,
            ygridvisible = false,
            xlabelvisible = true,
            ylabelvisible = true,
            xticklabelsvisible = true,
            yticklabelsvisible = true,
            xtickalign = 1,
            ytickalign = 1,
            xtickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            ytickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            xtickwidth = border,
            ytickwidth = border,
            xlabel = L"\mu",
            ylabel = L"\exp(-\Delta V)",
            xlabelsize = labels,
            ylabelsize = labels,
            xticklabelsize = labels,
            yticklabelsize = labels,
           )

ax2M = Axis(fig[2,2],
            limits = (1.8, 2.6, 0.0, 1.0),
            spinewidth = border,
            xgridvisible = false,
            ygridvisible = false,
            xlabelvisible = true,
            ylabelvisible = false,
            xticklabelsvisible = true,
            yticklabelsvisible = false,
            xtickalign = 1,
            ytickalign = 1,
            xtickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            ytickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            xtickwidth = border,
            ytickwidth = border,
            xlabel = L"\mu",
            ylabel = L"\exp(-\Delta V)",
            xlabelsize = labels,
            ylabelsize = labels,
            xticklabelsize = labels,
            yticklabelsize = labels,
           )

ax2R = Axis(fig[2,3],
            limits = (0.1, 1.2, 0.0, 1.0),
            spinewidth = border,
            xgridvisible = false,
            ygridvisible = false,
            xlabelvisible = true,
            ylabelvisible = false,
            xticklabelsvisible = true,
            yticklabelsvisible = false,
            xtickalign = 1,
            ytickalign = 1,
            xtickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            ytickformat = values -> ["$(trunc(value, digits=3))" for value in values],
            xtickwidth = border,
            ytickwidth = border,
            xlabel = L"\mu",
            ylabel = L"\exp(-\Delta V)",
            xlabelsize = labels,
            ylabelsize = labels,
            xticklabelsize = labels,
            yticklabelsize = labels,
           )
