"""
    Figures layout

Generation of the layouts and formats of the figures.
"""

# Specify the figure dimensions and style
fig = Figure(; size = (1200, 900), 
             #figure_padding = (60,60,30,30), 
             #backgroundcolor = :white
            )

# Set thickness and size of axes elements 
border = 2.0
labels = 20
ticks = 22

# Set boundaries of the potential range
upper = 4
lower = -8

# μ = -0.9
axT_1 = Axis(fig[1,1], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = true,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_1",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axT_2 = Axis(fig[1,2], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = false,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_2",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axT_3 = Axis(fig[1,3], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = false,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_3",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axT_4 = Axis(fig[1,4], limits = (-2, 2, -1, 1),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = true,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xticks = [-2,0,2],
             yticks = [-1,0,1],
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"x",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

# μ = -0.6
axM_1 = Axis(fig[2,1], limits = (nothing, nothing, 0, nothing), 
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = true,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_1",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axM_2 = Axis(fig[2,2], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = false,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_2",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axM_3 = Axis(fig[2,3], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = false,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_3",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axM_4 = Axis(fig[2,4], limits = (-2, 2, -1, 1),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = false,
             ylabelvisible = true,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xticks = [-2,0,2],
             yticks = [-1,0,1],
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"x",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

# μ = -0.3
axB_1 = Axis(fig[3,1], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = true,
             ylabelvisible = true,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_1",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axB_2 = Axis(fig[3,2], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = true,
             ylabelvisible = false,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_2",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axB_3 = Axis(fig[3,3], limits = (nothing, nothing, 0, nothing),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = true,
             ylabelvisible = false,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"\theta_3",
             ylabel = L"\text{distribution}",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

axB_4 = Axis(fig[3,4], limits = (-2, 2, -1, 1),
             spinewidth = border,
             xgridvisible = false,
             ygridvisible = false,
             xlabelvisible = true,
             ylabelvisible = true,
             xticklabelsvisible = true,
             yticklabelsvisible = true,
             xtickalign = 1,
             ytickalign = 1,
             xticks = [-2,0,2],
             yticks = [-1,0,1],
             xtickwidth = border,
             ytickwidth = border,
             xlabel = L"x",
             xlabelsize = labels,
             ylabelsize = labels,
             xticklabelsize = labels,
             yticklabelsize = labels,
            )

# Arrays of axes
axes = [[axT_1, axT_2, axT_3, axT_4], [axM_1, axM_2, axM_3, axM_4], [axB_1, axB_2, axB_3, axB_4]]
